feat: adds completely revamped readme, cert-identity, input validation, and a variety of other cleanup/fixes. (#166)
* feat: adds completely revamped readme, cert-identity, input validation, and a variety of other cleanup/fixes.

* fix: release only image assets.

diff --git a/.github/workflows/rw-attest.yaml b/.github/workflows/rw-attest.yaml
--- a/.github/workflows/rw-attest.yaml
+++ b/.github/workflows/rw-attest.yaml
@@ -92,8 +92,15 @@ on:
       build-artifact-id:
         description: The artifact-id of the build artifacts.
         value: ${{ inputs.build-type == 'blob' && jobs.build.outputs.build-artifact-id }}
+      all-attestations-artifact-id:
+        description: The artifact-id of all attestation artifacts.
+        value: ${{ inputs.build-type == 'blob' && jobs.upload-attestations.outputs.all-attestations }}
 
 permissions: {}
+
+env:
+  ARTIFACTS_FOLDER: ./artifacts
+  ATTESTATIONS_FOLDER: ./attestations
 
 jobs:
   build:
@@ -112,8 +119,20 @@ jobs:
         run: |
           echo "Job is running on a self-hosted runner. Terminating job..."
           exit 1
+      - name: Validate Inputs
+        run: |
+          if [[ "${{ inputs.build-type }}" == "image" && -z "${{ inputs.subject-name }}" ]]; then
+            echo "Error: subject-name is required for build-type 'image'."
+            exit 1
+          elif [[ "${{ inputs.build-type }}" == "blob" && -z "${{ inputs.subject-path }}" ]]; then
+            echo "Error: subject-path is required for build-type 'blob'."
+            exit 1
+          fi
       - name: Checkout code
         uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
+        with:
+          ref: ${{ github.sha }}
+          persist-credentials: false
       - name: Build Image
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
         id: build-image
@@ -157,17 +176,16 @@ jobs:
       packages: write
       contents: read
     env:
-      ARTIFACTS_FOLDER: ./artifacts
-      ATTESTATIONS_FOLDER: ./attestations
+      ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
     outputs:
       build-artifact-id: ${{ steps.upload-provenance.outputs.artifact-id }}
     steps:
-      - name: Check runner type
+      - name: Check Runner Type
         if: ${{ runner.environment != 'github-hosted' }}
         run: |
           echo "Job is running on a self-hosted runner. Terminating job..."
           exit 1
-      - name: Log in to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
         with:
@@ -176,12 +194,9 @@ jobs:
           password: ${{ github.token }}
       - run: npm install @actions/artifact@2.1.9
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
-      - name: download-artifact
+      - name: Download Blob Artifact(s)
         if: ${{ inputs.build-type == 'blob' }}
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        env:
-          ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
-          ARTIFACTS_FOLDER: ./artifacts
         with:
           script: |
             const { DefaultArtifactClient } = require('@actions/artifact');
@@ -194,28 +209,26 @@ jobs:
 
             await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
             console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
-      - name: List downloaded artifacts
-        if: ${{ inputs.build-type == 'blob' }}
-        run: ls -althR ./artifacts
       - name: Attest Provenance
         id: attest-build-provenance
         uses: actions/attest-build-provenance@1c608d11d69870c2092266b3f9a6f3abbf17002c # v1.4.3
         with:
           subject-name: ${{ inputs.build-type == 'image' && inputs.subject-name || '' }}
           subject-digest: ${{ inputs.build-type == 'image' && needs.build.outputs.image-digest || '' }}
-          subject-path: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
+          subject-path: ${{ inputs.build-type == 'blob' && format('{0}/{1}', env.ARTIFACTS_FOLDER, inputs.subject-path) || '' }}
           github-token: ${{ github.token }}
           push-to-registry: ${{ inputs.build-type == 'image' && 'true' || 'false' }}
       - name: Rename Provenance Bundle
         run: |
-          mkdir ./attestations
-          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ./attestations/attest-build-provenance-attestation.jsonl
+          mkdir ${{ env.ATTESTATIONS_FOLDER }}
+          mv ${{ steps.attest-build-provenance.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
       - name: Upload Provenance Sigstore Bundle
         id: upload-provenance
         uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
         with:
           name: attest-build-provenance
-          path: ./attestations/attest-build-provenance-attestation.jsonl
+          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-build-provenance-attestation.jsonl
+          if-no-files-found: error
 
   attest-metadata:
     runs-on: ${{ inputs.workflow-runner-label }}
@@ -225,15 +238,17 @@ jobs:
       attestations: write
       packages: write
       contents: read
+    env:
+      ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
     outputs:
       build-artifact-id: ${{ steps.upload-metadata.outputs.artifact-id }}
     steps:
-      - name: Check runner type
+      - name: Check Runner Type
         if: ${{ runner.environment != 'github-hosted' }}
         run: |
           echo "Job is running on a self-hosted runner. Terminating job..."
           exit 1
-      - name: Log in to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
         with:
@@ -242,12 +257,9 @@ jobs:
           password: ${{ github.token }}
       - run: npm install @actions/artifact@2.1.9
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
-      - name: download-artifact
+      - name: Download Blob Artifact(s)
         if: ${{ inputs.build-type == 'blob' }}
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        env:
-          ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
-          ARTIFACTS_FOLDER: ./artifacts
         with:
           script: |
             const { DefaultArtifactClient } = require('@actions/artifact');
@@ -260,9 +272,6 @@ jobs:
 
             await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
             console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
-      - name: List downloaded artifacts
-        if: ${{ inputs.build-type == 'blob' }}
-        run: ls -althR ./artifacts
       - run: |
           echo ${{ github.workflow }}
           echo ${{ github.workflow_ref }}
@@ -304,39 +313,41 @@ jobs:
           push-to-registry: ${{ inputs.build-type == 'image' && 'true' || 'false' }}
           subject-name: ${{ inputs.build-type == 'image' && inputs['subject-name'] || '' }}
           subject-digest: ${{ inputs.build-type == 'image' && needs.build.outputs.image-digest || '' }}
-          subject-path: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
+          subject-path: ${{ inputs.build-type == 'blob' && format('{0}/{1}', env.ARTIFACTS_FOLDER, inputs.subject-path) || '' }}
       - name: Rename Metadata Bundle
         run: |
-          mkdir ./attestations
-          mv ${{ steps.attest-metadata.outputs.bundle-path }} ./attestations/attest-metadata-attestation.jsonl
+          mkdir ${{ env.ATTESTATIONS_FOLDER }}
+          mv ${{ steps.attest-metadata.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
       - name: Upload Metadata Sigstore Bundle
         uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
         id: upload-metadata
         with:
           name: ${{ inputs.build-type == 'image' && 'image-metadata-attestation' || inputs.build-type == 'blob' && 'blob-metadata-attestation' }}
-          path: ./attestations/attest-metadata-attestation.jsonl
+          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-metadata-attestation.jsonl
           if-no-files-found: error
 
   attest-sbom:
     runs-on: ${{ inputs.workflow-runner-label }}
-    needs: [build, attest-metadata, attest-build]
+    needs: build
     permissions:
       id-token: write
       attestations: write
-      packages: write
       # the below permissions are required for a private repo to read the sbom so it can upload
       # https://github.com/anchore/sbom-action/issues/468#issuecomment-2126467656
+      packages: write
       contents: write
       actions: read
+    env:
+      ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
     outputs:
       build-artifact-id: ${{ steps.upload-sbom.outputs.artifact-id }}
     steps:
-      - name: Check runner type
+      - name: Check Runner Type
         if: ${{ runner.environment != 'github-hosted' }}
         run: |
           echo "Job is running on a self-hosted runner. Terminating job..."
           exit 1
-      - name: Log in to GitHub Container Registry
+      - name: Login to GitHub Container Registry
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
         with:
@@ -345,12 +356,9 @@ jobs:
           password: ${{ github.token }}
       - run: npm install @actions/artifact@2.1.9
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
-      - name: download-artifact
+      - name: Download Blob Artifact(s)
         if: ${{ inputs.build-type == 'blob' }}
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        env:
-          ARTIFACT_ID: ${{ needs.build.outputs.build-artifact-id }}
-          ARTIFACTS_FOLDER: ./artifacts
         with:
           script: |
             const { DefaultArtifactClient } = require('@actions/artifact');
@@ -363,15 +371,11 @@ jobs:
 
             await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
             console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
-      - name: List downloaded artifacts
-        if: ${{ inputs.build-type == 'blob' }}
-        run: ls -althR ./artifacts
       - name: Generate SBOM
         uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
         with:
           image: ${{ inputs.build-type == 'image' && format('{0}/{1}@{2}', inputs.registry, github.repository, needs.build.outputs.image-digest) || '' }}
-          path: ${{ inputs.build-type == 'blob' && './artifacts' || '' }}
-          file: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
+          path: ${{ inputs.build-type == 'blob' && env.ARTIFACTS_FOLDER || '' }}
           format: ${{ inputs['sbom-format'] }}
           output-file: ${{ inputs['sbom-output-file'] }}
           github-token: ${{ github.token }}
@@ -383,26 +387,27 @@ jobs:
         with:
           subject-name: ${{ inputs.build-type == 'image' && inputs['subject-name'] || '' }}
           subject-digest: ${{ inputs.build-type == 'image' && needs.build.outputs.image-digest || '' }}
-          subject-path: ${{ inputs.build-type == 'blob' && format('./artifacts/{0}', inputs.subject-path) || '' }}
+          subject-path: ${{ inputs.build-type == 'blob' && env.ARTIFACTS_FOLDER || '' }}
           sbom-path: ${{ inputs['sbom-path'] }}
           github-token: ${{ github.token }}
           push-to-registry: ${{ inputs.build-type == 'image' && 'true' || 'false' }}
       - name: Rename SBOM Bundle
         run: |
-          mkdir ./attestations
-          mv ${{ steps.attest-sbom.outputs.bundle-path }} ./attestations/attest-sbom-attestation.jsonl
+          mkdir ${{ env.ATTESTATIONS_FOLDER }}
+          mv ${{ steps.attest-sbom.outputs.bundle-path }} ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
       - name: Upload SBOM Attestation
         id: upload-sbom
         uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
         with:
           name: attest-sbom
-          path: ./attestations/attest-sbom-attestation.jsonl
+          path: ${{ env.ATTESTATIONS_FOLDER }}/attest-sbom-attestation.jsonl
+          if-no-files-found: error
 
   upload-attestations:
     runs-on: ${{ inputs.workflow-runner-label }}
     needs: [attest-build, attest-metadata, attest-sbom]
-    env:
-      ARTIFACTS_FOLDER: ./attestations
+    outputs:
+      all-attestations: ${{ steps.upload-all-attestations.outputs.artifact-id }}
     steps:
       - run: npm install @actions/artifact@2.1.9
       - name: Download Provenance Attestation
@@ -419,8 +424,8 @@ jobs:
               throw new Error('Artifact ID is not defined');
             }
 
-            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
-            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
+            await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
+            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
       - name: Download Metadata Attestation
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         env:
@@ -435,8 +440,8 @@ jobs:
               throw new Error('Artifact ID is not defined');
             }
 
-            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
-            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
+            await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
+            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
       - name: Download SBOM Attestation
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         env:
@@ -451,12 +456,12 @@ jobs:
               throw new Error('Artifact ID is not defined');
             }
 
-            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
-            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
+            await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
+            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
       - name: Upload All Attestations
-        id: all-attestations
+        id: upload-all-attestations
         uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
         with:
           name: all-attestations
-          path: ./attestations/*.jsonl
+          path: ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
           if-no-files-found: error
diff --git a/.github/workflows/rw-run-opa.yaml b/.github/workflows/rw-run-opa.yaml
--- a/.github/workflows/rw-run-opa.yaml
+++ b/.github/workflows/rw-run-opa.yaml
@@ -20,50 +20,78 @@ on:
         description: The digest of the image that was built and pushed
         required: false
         default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
-      build-artifact-id:
+      all-attestations-artifact-id:
         type: string
-        description: The artifact-id of the build artifacts.
+        description: The artifact-id of the attestation artifacts.
         required: false
-        default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.build-artifact-id }}
+        default: ${{ github.event.needs.build.outputs.all-attestations-artifact-id }}
       workflow-runner-label:
         type: string
         description: The label of the workflow runner
         default: ubuntu-latest
       registry:
-        description: >
-          The container registry to use.
+        description: The container registry to use.
         required: false
         type: string
         default: ghcr.io
+      opa-version:
+        description: The OPA version to use.
+        required: false
+        type: string
+        default: 0.67.1
+      policy-bundle-version:
+        description: The version of the policy bundle to download from https://github.com/liatrio/demo-gh-autogov-policy-library.
+        required: false
+        type: string
+
+permissions: {}
 
 env:
   GH_TOKEN: ${{ github.token }}
   RW_CW_POLICY_REPO_ACCESS: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}
+  ARTIFACT_ID: ${{ inputs.all-attestations-artifact-id }}
+  ATTESTATIONS_FOLDER: ./attestations
 
 jobs:
   run-opa:
+    permissions:
+      attestations: read
+      id-token: write
+      # packages: write is to delete stale images / read is only necessary for everything prior
+      packages: write
     runs-on: ${{ inputs.workflow-runner-label }}
     steps:
+      - name: Check Runner Type
+        if: ${{ runner.environment != 'github-hosted' }}
+        run: |
+          echo "Job is running on a self-hosted runner. Terminating job..."
+          exit 1
+      - name: Validate Inputs
+        run: |
+          if [[ "${{ inputs.build-type }}" == "image" && -z "${{ inputs.image-digest }}" ]]; then
+            echo "Error: subject-digest is required for build-type 'image'."
+            exit 1
+          elif [[ "${{ inputs.build-type }}" == "blob" && -z "${{ inputs.all-attestations-artifact-id }}" ]]; then
+            echo "Error: subject-path is required for build-type 'blob'."
+            exit 1
+          fi
+      - name: Setup OPA
+        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image'|| inputs.build-type == 'blob' }}
+        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
+        with:
+          version: ${{ inputs.opa-version }}
       - name: Log in to GitHub Container Registry
-        if: ${{ inputs.build-type == 'image' }}
+        if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
         with:
           registry: ${{ inputs.registry }}
           username: ${{ github.actor }}
           password: ${{ github.token }}
-      - name: Setup OPA
-        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
-        with:
-          version: 0.67.1
       - run: npm install @actions/artifact@2.1.9
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
-      - name: Download Blob Artifact
+      - name: Download Sigstore Bundle(s)
         if: ${{ inputs.build-type == 'blob' }}
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        env:
-          ARTIFACT_ID: ${{ inputs.build-artifact-id }}
-          ARTIFACTS_FOLDER: ./artifacts
-          ATTESTATIONS_FOLDER: ./attestations
         with:
           script: |
             const { DefaultArtifactClient } = require('@actions/artifact');
@@ -74,42 +102,38 @@ jobs:
               throw new Error('Artifact ID is not defined');
             }
 
-            await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
-            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
-      - name: List Downloaded Blob Artifacts
-        if: ${{ inputs.build-type == 'blob' }}
-        run: ls -althR ./artifacts
-      - name: Download artifacts for blob
-        if: ${{ inputs.build-type == 'blob' }}
-        run: |
-          if [ -d "./artifacts" ]; then
-            for FILE in "./artifacts"/*; do
-              gh attestation download "$FILE" -o liatrio
-            done
-          else
-            echo "Directory ./artifacts does not exist"
-            exit 1
-          fi
-      - name: list downloaded sigstore bundle(s)
-        if: ${{ inputs.build-type == 'blob' }}
-        run: |
-          set -x
-          ls -althR ./artifacts
-          ls -althR *.jsonl
-      - name: cat sigstore bundle
-        if: ${{ inputs.build-type == 'blob' }}
-        run: |
-          set -x
-          cat *.jsonl | jq -r '.dsseEnvelope.payload' | base64 -d | jq -r
-      - name: Download artifact attestation for image
+            await artifactClient.downloadArtifact(artifactId, { path: process.env.ATTESTATIONS_FOLDER });
+            console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ATTESTATIONS_FOLDER}`);
+      # - name: Download artifacts for blob
+      #   if: ${{ inputs.build-type == 'blob' }}
+      #   run: |
+      #     if [ -d "./artifacts" ]; then
+      #       for FILE in "./artifacts"/*; do
+      #         gh attestation download "$FILE" -o liatrio
+      #       done
+      #     else
+      #       echo "Directory ./artifacts does not exist"
+      #       exit 1
+      #     fi
+      - name: Download Image Artifact Attestation(s)
         if: ${{ inputs.build-type == 'image' }}
         run: |
-          gh attestation download oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} -o liatrio
+          mkdir ${{ env.ATTESTATIONS_FOLDER }}; cd ${{ env.ATTESTATIONS_FOLDER }}
+          gh attestation download \
+            oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} \
+            -o liatrio
+      - name: Process Sigstore Bundle(s)
+        run: |
+          set +x
+          jq -s . ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl \
+          > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json
+          rm ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
+          cat ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json | jq -r
       - name: Download Policy Bundle
         run: |
           set +x
           export GH_TOKEN=${{ env.RW_CW_POLICY_REPO_ACCESS }}
-          gh release download \
+          gh release download ${{ inputs.policy-bundle-version }} \
             --repo liatrio/demo-gh-autogov-policy-library \
             --pattern "bundle.tar.gz"
       - name: Run OPA Evals
@@ -118,7 +142,7 @@ jobs:
           set -x
           opa eval \
             --fail \
-            --input <(jq -s . ${{ inputs.image-digest.jsonl || '*.jsonl' }}) \
+            --input ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
             --bundle "bundle.tar.gz" \
             "data.governance.allow" >\
           policy-evaluation.json
@@ -129,7 +153,7 @@ jobs:
           set -x
           opa eval \
             --fail \
-            --input <(jq -s . ${{ inputs.image-digest.jsonl || '*.jsonl' }}) \
+            --input ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
             --bundle "bundle.tar.gz" \
             "data.governance.violations" >\
           policy-evaluation.json
@@ -163,7 +187,7 @@ jobs:
               | .key + ":\n" + (.value | map("- " + .) | join("\n")) + "\n"
               ' results >> $GITHUB_STEP_SUMMARY
           fi
-      - name: Upload results
+      - name: Upload Results
         uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
         with:
           name: ${{ inputs.build-type == 'image' && 'image-results' || inputs.build-type == 'blob' && 'blob-results' }}
@@ -172,11 +196,14 @@ jobs:
       # ______________#
       # image cleaner #
       # ______________#
-      - uses: actions/delete-package-versions@abd519f0d4139a1c79766c4859d3a301fb3a8daa
+      - name: Delete Stale Image(s)
+        if: ${{ inputs.build-type == 'image' }}
+        uses: actions/delete-package-versions@abd519f0d4139a1c79766c4859d3a301fb3a8daa # v5.0.0
+        continue-on-error: true
         with:
           package-name: ${{ github.event.repository.name }}
-          package-type: "container"
+          package-type: 'container'
           owner: ${{ github.repository_owner }}
-          min-versions-to-keep: 0
-          ignore-versions: '^v(0|[1-9]\d*)\.0\.0$' # currently does not work as per https://github.com/actions/delete-package-versions/issues/88
-          delete-only-untagged-versions: "true"
+          min-versions-to-keep: 100
+          ignore-versions: '^v(0|[1-9]\d*)\.0\.0$' # currently only works against the sha https://github.com/actions/delete-package-versions/issues/121#issuecomment-2237110213
+          delete-only-untagged-versions: 'true'
diff --git a/.github/workflows/rw-verify.yaml b/.github/workflows/rw-verify.yaml
--- a/.github/workflows/rw-verify.yaml
+++ b/.github/workflows/rw-verify.yaml
@@ -24,9 +24,16 @@ on:
         type: string
         description: The artifact-id of the build artifacts.
         default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.build-artifact-id }}
-      verify_tag:
+      all-attestations-artifact-id:
         type: string
-        description: Optional tag for verification
+        description: The artifact-id of the attestation artifacts.
+        required: false
+        default: ${{ github.event.needs.build.outputs.all-attestations-artifact-id }}
+      cert-identity:
+        type: string
+        description: >
+          The --cert-identity of the signer workflow, or builder, used in the verify job ensuring artifacts and attestations can be verified with the gh-cli.
+        default: https://github.com/liatrio/demo-gh-autogov-workflows/.github/workflows/rw-attest.yaml@refs/heads/main
         required: false
       workflow-runner-label:
         type: string
@@ -40,21 +47,34 @@ on:
         type: string
         default: 'ghcr.io'
 
+permissions: {}
+
 env:
   GH_TOKEN: ${{ github.token }}
 
 jobs:
   verify:
+    permissions:
+      id-token: write
+      attestations: read
+      packages: read
     runs-on: ${{ inputs.workflow-runner-label }}
     steps:
-      - name: Check runner type
+      - name: Check Runner Type
         if: ${{ runner.environment != 'github-hosted' }}
         run: |
           echo "Job is running on a self-hosted runner. Terminating job..."
           exit 1
-      - name: Checkout code
-        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
-      - name: Log in to GitHub Container Registry
+      - name: Validate Inputs
+        run: |
+          if [[ "${{ inputs.build-type }}" == "image" && -z "${{ inputs.image-digest }}" ]]; then
+            echo "Error: subject-digest is required for build-type 'image'."
+            exit 1
+          elif [[ "${{ inputs.build-type }}" == "blob" && -z "${{ inputs.build-artifact-id}}" ]]; then
+            echo "Error: build-artifact-id is required for build-type 'blob'."
+            exit 1
+          fi
+      - name: Login to GitHub Container Registry
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'image' }}
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
         with:
@@ -63,7 +83,7 @@ jobs:
           password: ${{ github.token }}
       - run: npm install @actions/artifact@2.1.9
         if: ${{ runner.environment == 'github-hosted' && inputs.build-type == 'blob' }}
-      - name: download-artifact
+      - name: Download Blob Artifact(s)
         if: ${{ inputs.build-type == 'blob' }}
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
         env:
@@ -81,35 +101,23 @@ jobs:
 
             await artifactClient.downloadArtifact(artifactId, { path: process.env.ARTIFACTS_FOLDER });
             console.log(`Downloaded artifact with ID: ${artifactId} to ${process.env.ARTIFACTS_FOLDER}`);
-      - name: List downloaded artifacts
+      - name: List Downloaded Blob Artifact(s)
         if: ${{ inputs.build-type == 'blob' }}
         run: ls -althR ./artifacts
-      - name: Check if in workflow repo
-        if: ${{ github.repository == 'liatrio/demo-gh-autogov-workflows' }}
-        run: echo "verify_tag=${{ github.ref }}" >> "$GITHUB_ENV"
-      - name: Get latest commit SHA from main
-        if: ${{ github.repository != 'liatrio/demo-gh-autogov-workflows' && !inputs.verify_tag }}
-        env:
-          GH_TOKEN: ${{ secrets.RW_CW_POLICY_REPO_ACCESS }}
-        run: |
-          latest_sha=$(gh api /repos/liatrio/demo-gh-autogov-workflows/commits/main | jq -r '.sha')
-          echo "verify_tag=$latest_sha" >> $GITHUB_ENV
-      - name: Set verify_tag from input
-        if: ${{ inputs.verify_tag }}
-        run: echo "verify_tag=${{ inputs.verify_tag }}" >> $GITHUB_ENV
-      - name: Verify attestation
+      - name: Verify Image Attestation(s)
         if: ${{ inputs.build-type == 'image' }}
         run: |
+          set +x
           gh attestation verify \
             oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} \
             --repo ${{ github.repository }} \
             --deny-self-hosted-runners \
             --cert-identity \
-            "https://github.com/${{ github.repository }}/.github/workflows/rw-attest.yaml@${{ env.verify_tag }}" \
+            "${{ inputs.cert-identity }}" \
             --format json \
             --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
-            | grep "^${{ env.verify_tag }}$"
-      - name: Verify blob attestation
+            | grep "^${{ github.ref }}$"
+      - name: Verify Blob Attestation(s)
         if: ${{ inputs.build-type == 'blob' }}
         env:
           ARTIFACTS_FOLDER: ./artifacts
@@ -119,7 +127,7 @@ jobs:
               $FILE \
               --deny-self-hosted-runners \
               --repo ${{ github.repository }} \
-              --cert-identity "https://github.com/${{ github.repository }}/.github/workflows/rw-attest.yaml@${{ env.verify_tag }}" \
+              --cert-identity "${{ inputs.cert-identity }}" \
               --format json --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
-            | grep "^${{ env.verify_tag }}$"
+            | grep "^${{ github.ref }}$"
           done
