feat: syncs w/ demo repo and adds octo-sts for custom tooling.

diff --git a/.github/workflows/rw-hp-run-opa.yaml b/.github/workflows/rw-hp-run-opa.yaml
--- a/.github/workflows/rw-hp-run-opa.yaml
+++ b/.github/workflows/rw-hp-run-opa.yaml
@@ -12,35 +12,35 @@ on:
           Subject name as it should appear in the attestation. Required unless
           "subject-path" is specified, in which case it will be inferred from the
           path.
-        default: ghcr.io/${{ github.repository }}
+        default: ${{ github.repository }}
         required: false
         type: string
       image-digest:
-        type: string
         description: The digest of the image that was built and pushed
-        required: false
         default: ${{ inputs.build-type == 'image' && github.event.needs.build.outputs.image-digest }}
+        required: false
+        type: string
       registry:
         description: The container registry to use.
+        default: ghcr.io
         required: false
         type: string
-        default: ghcr.io
       blob-artifact-id:
-        type: string
         description: The artifact-id of the build artifacts.
         default: ${{ inputs.build-type == 'blob' && github.event.needs.build.outputs.blob-artifact-id }}
-      workflow-runner-label:
         type: string
+      workflow-runner-label:
         description: The label of the workflow runner
         default: ubuntu-latest
+        type: string
       opa-version:
         description: The OPA version to use.
         required: false
         type: string
-        default: 0.67.1
+        default: v1.1.0
     outputs:
       results-artifact-id:
-        description: The image digest of the image that was built from the build-image job.
+        description: The artifact-id of the opa eval results artifact.
         value: ${{ jobs.run-opa-high-perms.outputs.results-artifact-id }}
 
 permissions: {}
@@ -49,6 +49,8 @@ env:
   GH_TOKEN: ${{ github.token }}
   ARTIFACTS_FOLDER: ./artifacts
   ATTESTATIONS_FOLDER: ./attestations
+  WORKFLOWS_REPO: liatrio-gh-autogov-workflows
+  POLICY_REPO_NAME: liatrio-rego-policy-library
 
 jobs:
   run-opa-high-perms:
@@ -67,13 +69,10 @@ jobs:
           echo "Job is running on a self-hosted runner. Terminating job..."
           exit 1
       - name: Validate Inputs
+        if: ${{ inputs.build-type == 'image' && (inputs.subject-name == '' || inputs.image-digest == '') }}
         run: |
-          if [[ "${{ inputs.build-type }}" == "image" ]]; then
-            if [[ -z "${{ inputs.subject-name }}" || -z "${{ inputs.image-digest }}" ]]; then
-              echo "Error: Both subject-name and image-digest are required for build-type 'image'."
-              exit 1
-            fi
-          fi
+          echo "Error: Both subject-name and image-digest are required for build-type 'image'."
+          exit 1
       - name: Setup OPA
         if: ${{ runner.environment == 'github-hosted' }}
         uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
@@ -90,7 +89,7 @@ jobs:
         run: mkdir ${{ env.ATTESTATIONS_FOLDER }} && mkdir ${{ env.ARTIFACTS_FOLDER }}
       - name: Install actions/artifact Library
         if: ${{ inputs.build-type == 'blob' }}
-        run: npm install @actions/artifact@2.1.11
+        run: npm install @actions/artifact@2.2.1
       - name: Download Blob Artifact(s)
         if: ${{ inputs.build-type == 'blob' }}
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
@@ -120,21 +119,19 @@ jobs:
         run: |
           cd ${{ env.ATTESTATIONS_FOLDER }}
           gh attestation download \
-            oci://${{ inputs.subject-name }}@${{ inputs.image-digest }} \
+            oci://${{ format('{0}/{1}@{2}', inputs.registry, github.repository, inputs.image-digest) }} \
             --repo ${{ github.repository }}
       - name: Process Sigstore Bundle(s)
         run: |
           set +x
-          jq -s . ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl \
-          > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json
-          rm ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
+          echo "Processing Sigstore bundles from ${{ env.ATTESTATIONS_FOLDER }}"
+          if ! jq -s . ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl > ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json; then
+            echo "Error: Failed to process Sigstore bundles"
+            exit 1
+          fi
+          rm -f ${{ env.ATTESTATIONS_FOLDER }}/*.jsonl
+          echo "Processed Sigstore bundle:"
           cat ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json | jq -r
-      - name: Log into GitHub Container Registry
-        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ github.token }}
       - name: Setup ORA
         uses: oras-project/setup-oras@5c0b487ce3fe0ce3ab0d034e63669e426e294e4d # v1.2.2
       - name: Download Policy Bundle
@@ -142,24 +139,39 @@ jobs:
           set +x
           oras pull \
             ghcr.io/${{ github.repository_owner }}/liatrio-rego-policy-library:latest
+      - name: Enable Dev Mode
+        if: github.repository == format('{0}/{1}', github.repository_owner, env.WORKFLOWS_REPO)
+        run: |
+          echo "Running in Dev Mode - creating dev-mode-bundle.json"
+          jq 'map(. + {"ignore_dependency_vulnerabilities": true})' \
+            ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
+            > ${{ env.ATTESTATIONS_FOLDER }}/dev-mode-bundle.json
+          echo "Dev Sigstore bundle created successfully"
+          cat ${{ env.ATTESTATIONS_FOLDER }}/dev-mode-bundle.json | jq -r
       - name: Run OPA Evals
         id: run-opa
+        env:
+          OPA_INPUT: ${{ env.ATTESTATIONS_FOLDER }}/${{ github.repository == format('{0}/{1}', github.repository_owner, env.WORKFLOWS_REPO) && 'dev-mode-bundle.json' || 'sigstore-bundle.json' }}
         run: |
           set -x
+          echo "Using input file: $OPA_INPUT"
           opa eval \
             --fail \
-            --input ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
+            --input "$OPA_INPUT" \
             --bundle "bundle.tar.gz" \
             "data.governance.allow" >\
           policy-evaluation.json
           cat policy-evaluation.json | jq -r
       - name: Output Violations if failed
         if: ${{ failure() && steps.run-opa.outcome == 'failure' }}
+        env:
+          INPUT_FILE: ${{ env.ATTESTATIONS_FOLDER }}/${{ github.repository == format('{0}/{1}', github.repository_owner, env.WORKFLOWS_REPO) && 'dev-mode-bundle.json' || 'sigstore-bundle.json' }}
         run: |
           set -x
+          echo "Using input file: $OPA_INPUT"
           opa eval \
             --fail \
-            --input ${{ env.ATTESTATIONS_FOLDER }}/sigstore-bundle.json \
+            --input "$INPUT_FILE" \
             --bundle "bundle.tar.gz" \
             "data.governance.violations" >\
           policy-evaluation.json
@@ -196,7 +208,7 @@ jobs:
       - name: Upload Results
         if: success() || failure()
         id: upload-results
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
         with:
           name: ${{ inputs.build-type == 'image' && 'image-results-' || inputs.build-type == 'blob' && 'blob-results-' }}${{ env.RESULT_STATUS }}
           path: results-${{ env.RESULT_STATUS }}
